### ISSUE TITLE
Adding a license to the project

### ISSUE THREAD

**Issue by MelonSpeedruns** [humbertodias/RetroUnityFE#6]
Hello there! Would it be possible to add a license to the project? I'm looking to use this repository for a project of mine, but I'd like to make sure I'm legally allowed to do so, so a license would be needed.

May I recommend the MIT license?

Thanks!

**Comment by humbertodias** [comment]
GPL 3 added https://github.com/humbertodias/RetroUnityFE/commit/e49adccbae6f0d274e3a747eae9663f3511be5a4
